"""Updates email column in user

Revision ID: 41f24226b489
Revises: 710b1c5da5ea
Create Date: 2022-05-18 10:52:21.688263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f24226b489'
down_revision = '710b1c5da5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time')
    # ### end Alembic commands ###
